"""Date created and updated

Revision ID: 24ae2e19cc07
Revises: 9a16494983e6
Create Date: 2025-08-17 14:52:22.313639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '24ae2e19cc07'
down_revision: Union[str, Sequence[str], None] = '9a16494983e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('order', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('product', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('product', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'updated_at')
    op.drop_column('product', 'created_at')
    op.drop_column('order', 'updated_at')
    op.drop_column('order', 'created_at')
    # ### end Alembic commands ###
