"""Product is main required

Revision ID: 5c379ffff238
Revises: cadd8a1695ac
Create Date: 2025-11-22 15:24:21.566674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c379ffff238'
down_revision: Union[str, Sequence[str], None] = 'cadd8a1695ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'is_main',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'is_main',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
