"""Product sizes

Revision ID: 5da7f3df19a2
Revises: b2b3c33e7874
Create Date: 2026-01-04 11:24:51.728107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5da7f3df19a2'
down_revision: Union[str, Sequence[str], None] = 'b2b3c33e7874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('weight', sa.Numeric(), nullable=True))
    op.add_column('product', sa.Column('width', sa.Numeric(), nullable=True))
    op.add_column('product', sa.Column('height', sa.Numeric(), nullable=True))
    op.add_column('product', sa.Column('length', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'length')
    op.drop_column('product', 'height')
    op.drop_column('product', 'width')
    op.drop_column('product', 'weight')
    # ### end Alembic commands ###
