"""Cargo type

Revision ID: 637945a5569a
Revises: e31bde81997a
Create Date: 2026-03-25 18:24:56.741255

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "637945a5569a"
down_revision: Union[str, Sequence[str], None] = "e31bde81997a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    cargotype_enum = sa.Enum(
        "SMALL", "MEDIUM", "LARGE", "EXTRA_LARGE", name="cargotype"
    )
    cargotype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("product", sa.Column("cargo_type", cargotype_enum, nullable=True))
    op.drop_column("product", "height")
    op.drop_column("product", "width")
    op.drop_column("product", "weight")
    op.drop_column("product", "length")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product", sa.Column("length", sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "product", sa.Column("weight", sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "product", sa.Column("width", sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "product", sa.Column("height", sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    op.drop_column("product", "cargo_type")
    op.execute("DROP TYPE IF EXISTS cargotype;")
    # ### end Alembic commands ###
