"""Coordinates

Revision ID: 648e44c1e272
Revises: a0d599804f82
Create Date: 2025-09-07 12:13:37.786889

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "648e44c1e272"
down_revision: Union[str, Sequence[str], None] = "a0d599804f82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orderdetail",
        sa.Column("latitude", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "orderdetail",
        sa.Column("longitude", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "orderdetail",
        sa.Column(
            "delivery_price",
            sa.Numeric(precision=12, scale=2),
            default=0,
            nullable=True,
        ),
    )
    # Step 2: Update existing NULL values with default
    op.execute("UPDATE orderdetail SET delivery_price = 0 WHERE delivery_price IS NULL")
    op.alter_column("orderdetail", "delivery_price", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orderdetail", "delivery_price")
    op.drop_column("orderdetail", "longitude")
    op.drop_column("orderdetail", "latitude")
    # ### end Alembic commands ###
