"""Product characteristics

Revision ID: 7a56c2477cb8
Revises: 648e44c1e272
Create Date: 2025-10-12 11:12:48.806217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a56c2477cb8'
down_revision: Union[str, Sequence[str], None] = '648e44c1e272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('characteristics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'characteristics')
    # ### end Alembic commands ###
