"""Order status column

Revision ID: 9a16494983e6
Revises: 22831905b521
Create Date: 2025-08-17 13:58:26.557302

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9a16494983e6"
down_revision: Union[str, Sequence[str], None] = "22831905b521"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE orderstatus AS ENUM ('created', 'cancelled', 'success')")
    op.add_column(
        "order",
        sa.Column(
            "status",
            sa.Enum("CREATED", "CANCELLED", "SUCCESS", name="orderstatus"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "status")
    # ### end Alembic commands ###
