"""Product is available

Revision ID: c809485f54c3
Revises: 637945a5569a
Create Date: 2026-05-30 12:03:17.235933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c809485f54c3"
down_revision: Union[str, Sequence[str], None] = "637945a5569a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Шаг 1: nullable=True
    op.add_column("product", sa.Column("is_available", sa.Boolean(), nullable=True))

    # Шаг 2: заполнить существующие строки
    op.execute("UPDATE product SET is_available = true WHERE is_available IS NULL")

    # Шаг 3: сделать NOT NULL
    op.alter_column("product", "is_available", nullable=False)
    op.alter_column(
        "product",
        "cargo_type",
        existing_type=postgresql.ENUM(
            "SMALL", "MEDIUM", "LARGE", "EXTRA_LARGE", name="cargotype"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product",
        "cargo_type",
        existing_type=postgresql.ENUM(
            "SMALL", "MEDIUM", "LARGE", "EXTRA_LARGE", name="cargotype"
        ),
        nullable=True,
    )
    op.drop_column("product", "is_available")
    # ### end Alembic commands ###
