"""Product is main

Revision ID: cadd8a1695ac
Revises: d6cbe9f705e8
Create Date: 2025-11-22 15:23:26.657443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cadd8a1695ac'
down_revision: Union[str, Sequence[str], None] = 'd6cbe9f705e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_main', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'is_main')
    # ### end Alembic commands ###
