"""Add amount to order

Revision ID: d87105c9f73e
Revises: 5da7f3df19a2
Create Date: 2026-01-22 17:53:21.426400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd87105c9f73e'
down_revision: Union[str, Sequence[str], None] = '5da7f3df19a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('order', sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('order', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('payment_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'payment_data')
    op.drop_column('order', 'external_id')
    op.drop_column('order', 'amount_paid')
    op.drop_column('order', 'amount')
    # ### end Alembic commands ###
